FROM ubuntu:noble

# Use bash instead of sh to be able to use process substitution in RUN commands.
SHELL ["/bin/bash", "-c"]

# Remove default ubuntu user
RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu

# Install software!
#
# We're basing this image on ubuntu and I'm trusting the default apt repos.
#
# Unfortunately we're getting a very old podman version this way.
#
RUN apt update && apt upgrade -y && \
  export DEBIAN_FRONTEND="noninteractive" && \
  export TZ="Europe/Stockholm" && \
  apt install -y \
  ack \
  bash-completion \
  build-essential \
  curl \
  dconf-cli \
  dbus-x11 \
  file \
  fonts-noto \
  git \
  gitk \
  gnome-icon-theme \
  gnome-terminal \
  gpg \
  jq \
  libcanberra-gtk-module \
  libcanberra-gtk3-module \
  libglib2.0-bin \
  libxml2-dev \
  libxslt-dev \
  meld \
  net-tools \
  netcat-openbsd \
  openjdk-21-jdk \
  openjdk-21-source \
  podman \
  python3 \
  python3-dev \
  python3-pip \
  python3-tk \
  python3-venv \
  ruby-full \
  sudo \
  unzip \
  vim \
  wget \
  x11-apps \
  zlib1g-dev

# Make podman use remote by default.
# This is much easier to achieve by using the CONTAINER_HOST environment variable on more modern versions of podman.
RUN \
  mv /usr/bin/podman /usr/bin/podman-local && \
  echo -e '#!/bin/bash\npodman-local --remote "$@"\nexit $?' > /usr/bin/podman && \
  chmod 755 /usr/bin/podman

# Yq is not published in any apt repo that I trust, so let's take it directly from github.
#
# I'm locking down the specific version and verifying the binary's sha512 sum to protect against supply chain attacks.
# Obviously, when we upgrade yq version we need to update the checksum too.
#
# If the sha512 checksum mismatches then the RUN process will fail. But note how the tar command inside the process
# substitution is asynchronous and may fail without that error propagating to the parent process. In that case we're
# saved by the mv command which WILL fail if the tar command didn't manage to extract the file.
RUN \
  cd /usr/bin && \
  curl -L https://github.com/mikefarah/yq/releases/download/v4.53.2/yq_linux_amd64.tar.gz | \
    tee >(tar xz --no-same-owner -f- ./yq_linux_amd64) | \
    sha512sum -c <(echo '0d197c8ac4437d4be7fbf40148e02baebc624c3d1564230ef972390bb7e13da87e2ab94d0243c5e1cfedbc980526cfdf2142b09efc282219d374a196d2619297 -') && \
  mv yq_linux_amd64 yq

# Maven
#
# See above for detailed explanation about what's going on here. Here the cd command will save us in case the
# substituted process fails.
#
RUN \
  cd /opt && \
  curl -L https://dlcdn.apache.org/maven/maven-3/3.9.15/binaries/apache-maven-3.9.15-bin.tar.gz | \
    tee >(tar xz --no-same-owner -f-) | \
    sha512sum -c <(echo "33d81e0ec785f0207e3e5e3ffb61863e1dca5784c15ac3fb5ff105f69cffbea484eb8d473ea60467a63f7b0570eef8622f2fed8eee96acbe668aa313391cddb3 -") && \
  cd apache-maven-* && \
  MAVENHOME=$(pwd) && \
  cd /usr/bin && \
  ln -s ${MAVENHOME}/bin/mvn mvn

# Eclipse
#
# See above for detailed explanation about what's going on here. Here the cd command will save us in case the
# substituted process fails.
# 
RUN \
  cd /opt && \
  curl -L 'https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2026-03/R/eclipse-jee-2026-03-R-linux-gtk-x86_64.tar.gz&r=1' | \
    tee >(tar xz --no-same-owner -f-) | \
    sha512sum -c <(echo "2fd59ada93f8e4aa38feb3ef6dfc82165e8be7f5b5c86140d5426264246f185a0cc48e80fc06b7c4ef7a356a56ece91a2a7df859f545ce9d2bb2f1337986581d -") && \
  cd eclipse* && \
  ECLIPSEHOME=$(pwd) && \
  cd /usr/bin && \
  ln -s ${ECLIPSEHOME}/eclipse eclipse && \
  echo '-Dorg.eclipse.oomph.setup.donate=false' >> /opt/eclipse/eclipse.ini

# Protobuf compiler
RUN \
  cd /usr/bin && \
  curl -L https://github.com/protocolbuffers/protobuf/releases/download/v25.1/protoc-25.1-linux-x86_64.zip --output protoc.zip && \
  sha512sum -c <(echo "75da030a2c9fb3ccd689a2beaeab42d44803b314410f6578c7af030d1ac29d3de1260a4fb50eca5c8efbcd1ac4a94b4a130e45afebf8a182d6c1d3241a2f8dba protoc.zip") && \
  unzip -p protoc.zip bin/protoc > protoc && \
  chmod 755 protoc && \
  rm protoc.zip

# Node.js
RUN \
  cd /opt && \
  curl -L https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.gz | \
    tee >(tar xz --no-same-owner -f-) | \
    sha256sum -c <(echo "80b978a9fe544b1892e73a4bf89e0b3792b1d459b621874efdc2ddd2270c03fe -") && \
  cd node-* && \
  NODEHOME=$(pwd) && \
  cd /usr/bin && \
  ln -s ${NODEHOME}/bin/corepack corepack && \
  ln -s ${NODEHOME}/bin/node node && \
  ln -s ${NODEHOME}/bin/npm npm && \
  ln -s ${NODEHOME}/bin/npx npx

# AWS CLI
RUN \
  mkdir /tmp/aws-cli-install
COPY aws-cli-pgp-key.pub /tmp/aws-cli-install/aws-cli-pgp-key.pub
RUN \
  cd /tmp/aws-cli-install && \
  gpg --import aws-cli-pgp-key.pub && \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig" -o "awscliv2.sig" && \
  gpg --verify awscliv2.sig awscliv2.zip && \
  unzip awscliv2.zip && \
  ./aws/install && \
  cd / && \
  rm -rf /tmp/aws-cli-install

# Java Preferences Utility
RUN \
  mkdir /opt/javaprefs && \
  chmod 755 /opt/javaprefs
COPY javauserprefadd /opt/javaprefs/.
RUN \
  chmod 755 /opt/javaprefs/javauserprefadd && \
  cd /usr/bin && \
  ln -s /opt/javaprefs/javauserprefadd javauserprefadd

# Xidel
RUN \
  mkdir /tmp/xidel-install && \
  curl -L https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz | \
    tee >(tar xz --no-same-owner -f-) | \
    sha512sum -c <(echo "b4050dd198e7d5f35fc28fe0fb64246ddd85bb511a51b368fc6316082a1feb397137e07cd22d5e110fd233a600d078eb9122a50529d08c8c0d04e0bbf09e8113 -") && \
  cp xidel /usr/bin/. && \
  cd / && \
  rm -rf /tmp/xidel-install

# Minikube
RUN \
  mkdir /tmp/minikube-install && \
  cd /tmp/minikube-install && \
  curl -L https://storage.googleapis.com/minikube/releases/v1.37.0/minikube_1.37.0-0_amd64.deb --output minikube_1.37.0-0_amd64.deb && \
  sha512sum -c <(echo "8c08727dc0e18489e25af4518a2273ecd727588cc9e836288de1cf9a415b3fe5621d39fe871bc845e86a558791b832b983a8bc673cc2cc10ee57b97a11dc5ec0 minikube_1.37.0-0_amd64.deb") && \
  dpkg -i minikube_1.37.0-0_amd64.deb && \
  cd / && \
  rm -rf /tmp/minikube-install

# Kubectl
RUN \
  mkdir /tmp/kubectl-install && \
  cd /tmp/kubectl-install && \
  curl -L https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl --output kubectl && \
  sha512sum -c <(echo "bc4f4c98a2c4f7d872e5a8024dd0f47f73e1a5a6c8b833f265e7453c3c31f23555c3df1d921c5b3e8a0f6a1aae4954f0b5141db9c396c4206c947206eb34a398 kubectl") && \
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
  cd / && \
  rm -rf /tmp/kubectl-install

ARG USERID
ARG GROUPID
ARG USERNAME

# Create the user
RUN \
  groupadd -g $GROUPID $USERNAME && \
  useradd -u $USERID -g $GROUPID --create-home --home-dir /home/$USERNAME -s /bin/bash $USERNAME && \
  chown -R $USERNAME:$USERNAME /home/$USERNAME

# Claude Code
RUN \
  install -d -m 0755 /etc/apt/keyrings && \
  curl -fsSL https://downloads.claude.ai/keys/claude-code.asc -o /etc/apt/keyrings/claude-code.asc && \
  gpg --show-keys --with-colons /etc/apt/keyrings/claude-code.asc | \
    grep '^fpr:' | head -n1 | grep -F 'fpr:::::::::31DDDE24DDFAB679F42D7BD2BAA929FF1A7ECACE:' && \
  echo "deb [signed-by=/etc/apt/keyrings/claude-code.asc] https://downloads.claude.ai/claude-code/apt/stable stable main" | \
    sudo tee /etc/apt/sources.list.d/claude-code.list && \
  apt update && apt upgrade -y && \
  export DEBIAN_FRONTEND="noninteractive" && \
  export TZ="Europe/Stockholm" && \
  apt install -y \
  claude-code

# Go
RUN \
  cd /usr/local && \
  curl -L https://go.dev/dl/go1.26.3.linux-amd64.tar.gz | \
    tee >(tar xz --no-same-owner -f-) | \
    sha512sum -c <(echo "cc49ca9764b1dff5983d7635bc6e8f9fe71754bf48ec310a43512cef6103c4a88ed446e9b759742affa9bbcac507957fb9993011cb94343b88ba938c17632c28  -")

USER $USERNAME

# Minikube configuration
RUN \
  minikube config set rootless true

# JMeter and Custom Thread Groups plugin
# Must be installed as user, not root, otherwise plugin manager won't work with Taurus.
RUN \
  mkdir -p $HOME/.local/bin && \
  cd $HOME/.local && \
  curl -L https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz | \
    tee >(tar xz --no-same-owner -f-) | \
    sha512sum -c <(echo "5978a1a35edb5a7d428e270564ff49d2b1b257a65e17a759d259a9283fc17093e522fe46f474a043864aea6910683486340706d745fcdf3db1505fd71e689083 -") && \
  cd apache-jmeter-* && \
  JMETERHOME=$(pwd) && \
  cd $HOME/.local/bin && \
  ln -s ${JMETERHOME}/bin/jmeter jmeter && \
  cd ${JMETERHOME}/lib/ext && \
  curl -L https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.10/jmeter-plugins-manager-1.10.jar --output jmeter-plugins-manager-1.10.jar && \
  sha512sum -c <(echo "38af806a7c78473c032ba93c7a2e522674871f01616985a0b0522483977d58afdc444d18bd5590b8036c344ccf11d2fe61be807501d5edb6d4bdebc9050c43ae jmeter-plugins-manager-1.10.jar") && \
  cd ${JMETERHOME}/lib && \
  curl -L https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar --output cmdrunner-2.3.jar && \
  sha512sum -c <(echo "7f71fe42f4ead4ccddd68148e97a46b9262bdb05fe5e590a725331513549122dc64d4cb524635b2f0e3e7d3ee4bb3c2807738cd3c7e2d0d7a503ea78234dab51 cmdrunner-2.3.jar") && \
  java -cp ${JMETERHOME}/lib/ext/jmeter-plugins-manager-1.10.jar org.jmeterplugins.repository.PluginManagerCMDInstaller && \
  ${JMETERHOME}/bin/PluginsManagerCMD.sh install jpgc-casutg=2.10

# Use JMeter's SolarizedDarkTheme
RUN \
  javauserprefadd "/org/apache/jmeter/gui/action" "laf.command" "com.github.weisj.darklaf.DarkLaf:com.github.weisj.darklaf.theme.SolarizedDarkTheme"

# Default venv for python
RUN \
  python3 -m venv ~/.python/venvs/default
  
# Make sure we're using the latest pip
  RUN \
  export PATH="~/.python/venvs/default/bin:$PATH" && \
  pip install --upgrade pip wheel setuptools Cython

# Taurus
RUN \
  export PATH="~/.python/venvs/default/bin:$PATH" && \
  pip install bzt

# Taurus settings
# Taurus doesn't handle symlinks to jmeter well, so we need to specify the real path to jmeter
RUN \
  touch ~/.bzt-rc && \
  chmod 600 ~/.bzt-rc && \
  echo $'modules:\n\
  jmeter:\n\
    path: '$(readlink -f $HOME/.local/bin/jmeter)$'\n' >> ~/.bzt-rc

# Suppress sudo warning when starting terminal
RUN \
  touch ~/.sudo_as_admin_successful

# Beautiful default monospace font and no menubar in the terminal
RUN \
  dbus-launch gsettings set org.gnome.desktop.interface monospace-font-name "'DejaVu Sans Mono 14'" && \
  dbus-launch gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false

# Solarized color theme
#
# I'm checking out a specific gitsha of the gnome-terminal-colors-solarized repo to protect against supply chain
# attacks. Likewise, I'm downloading a specific gitsha of dircolors-solarized to be sure what I'm getting.
#
RUN \
  cd /tmp && \
  git clone https://github.com/aruhier/gnome-terminal-colors-solarized.git && \
  cd gnome-terminal-colors-solarized && \
  git reset --hard 9651c41df0f89e87feee0c798779abba0f9395e0 && \
  dbus-launch ./install.sh --skip-dircolors -s dark -p $(gsettings get org.gnome.Terminal.ProfilesList list | sed "s/.*'\([^']\{1,\}\)'.*/\1/") && \
  cd /tmp && \
  rm -rf /tmp/gnome-terminal-colors-solarized && \
  mkdir ~/.dir_colors && \
  chmod 700 ~/.dir_colors && \
  mkdir dircolors-solarized && \
  cd dircolors-solarized && \
  curl -L https://raw.github.com/seebi/dircolors-solarized/664dd4e91ff9600a8e8640ef59bc45dd7c86f18f/dircolors.ansi-light >> ~/.dir_colors/dircolors && \
  cd /tmp && \
  rm -rf dircolors-solarized

# Jekyll
RUN \
  export GEM_HOME="/home/$USERNAME/gems" && \
  gem install jekyll bundler

ARG BASHRC

# Nice .bashrc and .profile
RUN \
  touch ~/.bashrc && \
  chmod 700 ~/.bashrc && \
  echo 'export SHELL="/bin/bash"' >> ~/.bashrc && \
  echo 'eval `dircolors /home/'$USERNAME'/.dir_colors/dircolors`' >> ~/.profile && \
  echo 'export CHEESE_WEDGE=$(echo -e '"'"'\U1f9c0'"'"')' >> ~/.bashrc && \
  echo 'export COW_FACE=$(echo -e '"'"'\U1f42e'"'"')' >> ~/.bashrc && \
  echo 'export PADLOCK=$(echo -e '"'"'\U1f512'"'"')' >> ~/.bashrc && \
  echo 'export SPIRAL_SHELL=$(echo -e '"'"'\U1f41a'"'"')' >> ~/.bashrc && \
  echo 'export WEBKIT_DISABLE_COMPOSITING_MODE=1' >> ~/.bashrc  && \
  echo 'export TZ="Europe/Stockholm"' >> ~/.bashrc  && \
  echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc && \
  echo 'export PATH="$HOME/.local/bin:$HOME/gems/bin:~/.python/venvs/default/bin:/usr/local/go/bin:$PATH"' >> ~/.bashrc && \
  echo 'export SSH_AUTH_SOCK=/run/user/'$USERID'/keyring/ssh' >> ~/.bashrc && \
  echo 'export CONTAINER_HOST="unix:///run/user/1000/podman/podman.sock"' >> ~/.bashrc && \
  echo 'source <(kubectl completion bash)' >> ~/.bashrc && \
  echo 'PS1='"'"'${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $PADLOCK '"'"'' >> ~/.bashrc && \
  echo 'cd $HOME' >> ~/.bashrc && \
  echo "$BASHRC" >> ~/.bashrc

ARG FULLNAME
ARG EMAIL

# Git config
RUN \
  git config --global user.name "$FULLNAME" && \
  git config --global user.email "$EMAIL"

# Mount points
RUN \
  mkdir ~/Data && \
  chmod 755 ~/Data && \
  mkdir ~/Downloads && \
  chmod 755 ~/Downloads && \
  mkdir ~/.ssh && \
  chmod 700 ~/.ssh && \
  mkdir ~/.m2 && \
  chmod 700 ~/.m2 && \
  mkdir ~/.m2/repository && \
  chmod 700 ~/.m2/repository && \
  mkdir ~/.eclipse && \
  chmod 700 ~/.eclipse && \
  mkdir ~/eclipse-workspace && \
  chmod 700 ~/eclipse-workspace && \
  mkdir ~/source && \
  chmod 700 ~/source && \
  mkdir ~/.aws && \
  chmod 700 ~/.aws

# Eclipse preferences
RUN \
  mkdir -p                                            ~/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/
COPY org.eclipse.ui.workbench.prefs     /home/$USERNAME/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.workbench.prefs
COPY org.eclipse.ui.ide.prefs.workspace /home/$USERNAME/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.ide.prefs
COPY org.eclipse.jdt.ui.prefs           /home/$USERNAME/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.ui.prefs
COPY org.eclipse.ui.editors.prefs       /home/$USERNAME/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.ui.editors.prefs
COPY org.eclipse.wst.xml.core.prefs     /home/$USERNAME/eclipse-workspace/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.wst.xml.core.prefs
RUN \
  mkdir -p                                            ~/.eclipse/org.eclipse.platform_4.31.0_1473617060_linux_gtk_x86_64/configuration/.settings/
COPY org.eclipse.ui.ide.prefs           /home/$USERNAME/.eclipse/org.eclipse.platform_4.31.0_1473617060_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs
RUN \
  sed -i "s/%username%/$USERNAME/"      /home/$USERNAME/.eclipse/org.eclipse.platform_4.31.0_1473617060_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs

# Prevent gnome-terminal from looking for accessibility tools
ENV NO_AT_BRIDGE=1

CMD ["gnome-terminal", "--disable-factory"]
